Ticker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from. import views

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls',namespace = 'admin_honeypot')), 
    path('secure_admin/', admin.site.urls),
    path('', views.home, name= 'home'),
    path('store/', include('store.urls')),     
    path('carts/', include('carts.urls')),       
    path('accounts/', include('accounts.urls')),  
    path('orders/' , include('orders.urls')),    
]
urlpatterns +=  static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views


urlpatterns =[
    path('', views.cart, name = 'cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name = 'add_to_cart'),
    path('remove_cart/<int:product_id>/', views.remove_cart, name = 'remove_cart'),
    path('delete_cart_item/<int:product_id>/', views.delete_cart_item, name = 'delete_cart_item'),
    path('coupon_verify/', views.coupon_verify, name = 'coupon_verify'),
    path('coupon_confirm/', views.coupon_verify, name = 'coupon_confirm'),
    path('checkout/', views.checkout, name = 'checkout'),
    path('validate_coupon/', views.validate_coupon, name= 'validate_coupon'),
    path('get_address/' ,views.get_address, name = 'get_address'),
    path('add_cart/<int:id>' ,views.add_cart, name = 'add_cart'),
    
    # path('rem_cart/<int:id>' ,views.rem_cart, name = 'rem_cart')
    
]

store/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    
    path('', views.store, name= 'store'),     
    path('del_coupon/<int:id>/', views.del_coupon, name ='del_coupon'),
    path('order_mgmt/',views.order_management, name = 'order_management'),
    path('shipping_status/<int:id>',views.shipping_status, name = 'shipping_status'),
    path('order_tracking/<int:product_id>', views.order_tracking, name = 'order_tracking'),
    path('submit_review/<int:product_id>/', views.submit_review, name= 'submit_review'),
    path('coupon_management',views.coupon_management, name='coupon_management'),
    path('create_coupon', views.create_coupon, name ='create_coupon'),
    
    path('view_orders/<int:id>',views.view_orders, name = 'view_orders'),
    path('edit_order/<int:id>',views.edit_order, name = 'edit_order'),
    path('search/',views.search, name = 'search'),
    path('weekly_report/',views.weekly_report, name = 'weekly_report'),
    path('monthly_report/',views.monthly_report, name = 'monthly_report'),
    path('yearly_report/',views.yearly_report, name = 'yearly_report'),
   
    path('offer_mgmt_prod/',views.offer_management_prod, name = 'offer_management_prod'),
    path('offer_mgmt_view_products/',views.offer_management_view_products, name = 'offer_management_view_products'),
    path('offer_mgmt_cat/',views.offer_management_cat, name = 'offer_management_cat'),
    path('add_product_offer/<int:product_id>/',views.add_product_offer, name= 'add_product_offer'),
    path('add_category_offer/',views.add_category_offer, name= 'add_category_offer'),
    
    path('del_product_offer/<int:product_id>/',views.del_product_offer, name='del_product_offer'),
   
    path('del_category_offer/<int:category_id>/',views.del_category_offer, name='del_category_offer'),
    
    

    path('product_mgmt/',views.product_management, name = 'product_management'),
    
    path('add_product/',views.add_product, name = 'add_product'),
    path('del_product/<int:pk>',views.del_product, name = 'del_product'),
    path('edit_product/<slug:slug>',views.edit_product, name = 'edit_product'),
    path('add_category/',views.add_category, name = 'add_category'),
    path('user_mgmt/',views.user_management, name = 'user_management'), 
    path('del_user/<int:pk>',views.del_user, name = 'del_user'),
    path('block_user/<int:pk>',views.block_user, name = 'block_user'),
    path('category_mgmt/',views.category_management, name = 'category_management'),
    path('del_category/<int:pk>',views.del_category, name = 'del_category'),
    path('edit_category/<int:pk>',views.edit_category, name = 'edit_category'),
    path('category/<slug:category_slug>/', views.store, name= 'products_by_category'),     
    path('<slug:category_slug>/<slug:product_slug>/', views.product_view, name= 'product_view'),  

    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.deletion import CASCADE
from django.urls import reverse
from .utils import generate_ref_code




class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, email, password = None):
        if not email:
            raise ValueError("Email is required")

        user = self.model(
            email       = self.normalize_email(email),
            first_name  = first_name,
            last_name   = last_name,
    
            
        )
        user.is_active     = True
        user.set_password(password)
        user.save()
        return user



    def create_superuser(self, first_name, last_name, email, password,):
        user = self.create_user(
            email       = self.normalize_email(email),
            first_name  = first_name,
            last_name   = last_name,
            password    = password,


        ) 
        user.is_admin      = True
        user.is_active     = True
        user.is_staff      = True
        user.is_superadmin = True
        user.save()
        return user 


        
class Account(AbstractBaseUser):
    first_name     = models.CharField(max_length=50)
    last_name      = models.CharField(max_length=50)
    email          = models.EmailField(max_length=50, unique=True)
    phone          = models.CharField(max_length=20)
    referral       = models.CharField(max_length=12, blank = True)
    
    date_joined    = models.DateTimeField(auto_now_add=True)
    last_login     = models.DateTimeField(auto_now_add=True)
    is_admin       = models.BooleanField(default=False)
    is_staff       = models.BooleanField(default=False)
    is_active      = models.BooleanField(default=False)
    is_superadmin  = models.BooleanField(default=False)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']  

    objects = MyAccountManager()


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_abel):
        return True

    def get_user(self):
        return reverse('user_profile', args =[self.id])


class Address(models.Model):
    user  =models.ForeignKey(Account, on_delete=CASCADE, blank = True, null= True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)

    def __str__(self):
        return self.first_name



class Profile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to="profile_images", default = "default.jpeg")
    code = models.CharField(max_length=12, blank = True)
    recommended_by = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True, related_name='ref_by')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True, blank = True, null=True)

    def __str__(self):
        return self.user.first_name

    def get_recommended_profiles(self):
        qs = Profile.objects.all()
        my_recs = [p for p in qs if p.recommended_by == self.user]
        return my_recs
        # pass

        # my_recs = []
        # for profile in qs:
        #     if profile.recommended_by == self.user

    def save(self, *args, **kwargs):
        if self.code == "":
            code = generate_ref_code()
            self.code = code
        super().save(*args, **kwargs)

carts/models.py
from accounts.models import Account
from django.db import models
from store.models import Product
from accounts.models import Account

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True )

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete= models.CASCADE)
    cart    = models.ForeignKey(Cart, on_delete = models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)


    def sub_total(self):
        # print('in_sub_total')
        sub_total = 0
        if self.product.offer_price:
            if self.product.coupon_price:
                sub_total += (self.product.offer_price-self.product.coupon_price) * self.quantity
                # print(sub_total,'if')
            else:
                sub_total += self.product.offer_price * self.quantity
                # print(sub_total,'iffff')
        elif  self.product.coupon_price and not self.product.offer_price:              
                sub_total += self.product.coupon_price * self.quantity
                # print(sub_total,'if')
        else:
            sub_total +=(self.product.price * self.quantity)
            # print(sub_total)
        return sub_total




        # if self.product.offer_price:
        #     sub_total = self.product.offer_price * self.quantity
        # else:
        #     sub_total = self.product.price * self.quantity
        

    def __str__(self):
        return self.product.product_name

store/models.py
from django.db.models.aggregates import Avg, Count
from accounts.models import Account
from typing import FrozenSet
from django.db import models
from category.models import Category
from django.urls import reverse
from category.models import Category

# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=150, unique=True)
    slug  = models.SlugField(max_length=150, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price  = models.IntegerField()
    offer_price = models.IntegerField(blank=True, null=True)
    coupon_price = models.IntegerField(blank=True, null=True)
    image1 = models.ImageField(upload_to= 'photos/products')
    image2 = models.ImageField(upload_to= 'photos/products')
    image3 = models.ImageField(upload_to= 'photos/products')
    image4 = models.ImageField(upload_to= 'photos/products')
    stock  = models.IntegerField()
    is_available = models.BooleanField(default= True)
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    created_date  = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    brand= models.CharField(max_length=30)
    gender= models.CharField(max_length=30)
    strap_colour= models.CharField(max_length=30)
    water_resistance= models.CharField(max_length=30)
    analogue_or_digital= models.CharField(max_length=30)
    glass= models.CharField(max_length=30)
    strap_type= models.CharField(max_length=30)  
    model_name= models.CharField(max_length=30)


    def get_url(self):
        return reverse('product_view',args = [self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    def average_review(self):
        review = ReviewRating.objects.filter(product= self, status = True).aggregate(average = Avg('rating'))
        avg = 0
        if review['average'] is not None:
            avg = float(review['average']) 
        return avg
    
    def count_review(self):
        review_count = ReviewRating.objects.filter(product= self, status = True).aggregate(count = Count('id'))
        count = 0 
        if review_count['count'] is not None:
            count = int(review_count['count']) 
        return count



class ProductOffer(models.Model):
    offer_name  =models.CharField(max_length=25, blank= True, null = True)
    product = models.ForeignKey(Product, blank = True,null=True, on_delete=models.CASCADE)
    off_percentage = models.IntegerField(blank=True, null = True)
    valid_from = models.DateField(blank=True, null=True)
    valid_upto = models.DateField(blank=True, null=True)
    expired = models.BooleanField(default=True)

    def __str__(self):
        return self.offer_name

class CategoryOffer(models.Model):
    offer_name  =models.CharField(max_length=25, blank= True, null = True)
    category  = models.ForeignKey(Category, on_delete=models.CASCADE, blank= True, null = True)
    off_percentage = models.IntegerField(blank=True, null=True)
    valid_from = models.DateField()
    valid_upto = models.DateField()
    expired = models.BooleanField(default=True)

    def __str__(self):
        return self.offer_name 

class CouponCode(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    coupon_name = models.CharField(max_length=6)
    off_price = models.IntegerField()
    valid_from = models.DateField()
    valid_upto  = models.DateField()
    valid = models.BooleanField(default= False)

    def __str__(self):
        return self.coupon_name

class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject =  models.CharField(max_length=100, blank = True)
    review = models.TextField(max_length=500, blank = True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject



class Coupons(models.Model):
    coupon_name = models.CharField(max_length=6, unique =True)
    off_price = models.IntegerField()
    valid_from = models.DateField()
    valid_upto  = models.DateField()
    valid = models.BooleanField(default= True)

    def __str__(self):
        return self.coupon_name

    

store/forms.py
from django import forms
from .models import Product, ProductOffer, ReviewRating


class AddProduct(forms.ModelForm):  
    class Meta:
        model     = Product
        fields    = ['product_name', 'slug', 'price', 'description', 'category', 'image1','image2', 'image3','image4','stock', 'brand','gender', 'strap_colour','water_resistance','analogue_or_digital', 'glass','strap_type','model_name'] 

    def __init__(self, *args, **kwargs):
            super(AddProduct, self).__init__(*args, **kwargs)
            self.fields['description'].widget.attrs['id'] = 'desc'
            for field in self.fields:
                self.fields[field].widget.attrs['class'] = 'form-control'     
            

class ProductOfferForm(forms.ModelForm):
    class Meta:
        model = ProductOffer
        fields = ['offer_name', 'product', 'off_percentage','valid_from','valid_upto']


class ReviewForm(forms.ModelForm):
    class Meta:
        model =  ReviewRating
        fields = ['subject', 'review', 'rating']

templates/user/add_address.html
    




    {% extends 'user/base.html' %}
    {% load static %}
    {% block contend %}
    
    
    
    <style>
      .sidenav {
        width: 15rem;
        height: 25rem;
        top: 0;
        left: 0;
        background-color: #111;
        overflow-x: hidden;
        padding-top: 20px;
    
      }
    
      .sidenav a {
        padding: 6px 8px 6px 16px;
        text-decoration: none;
        font-size: 15px;
        color: #818181;
        display: block;
      }
    
      .sidenav a:hover {
        color: #f1f1f1;
      }
    
    
    
      @media screen and (max-height: 450px) {
        .sidenav {
          padding-top: 15px;
        }
    
        .sidenav a {
          font-size: 18px;
        }
      }
    </style>
    
    
    
    <div class="row">
      <div class="col-lg-3 mt-2">
        <div class="card" style="height: 100% ; width: 18rem;">
          <div class="card-body">
    
    
            <!-- <a href="#" class="btn btn-outline-dark my-3">User Profile</a><br>
              <a href="" class="btn btn-outline-dark my-3">Add Address</a><br>
              <a href="" class="btn btn-outline-dark my-3">Orders</a>
               -->
    
            <div class="sidenav">
              <a href="{% url 'user_profile' user.id %}" >Profile Info</a>
              <hr style="background-color: white;">
              <a href="{% url 'add_address' %}"  class="active"style="color: white;">Add New Address</a>
              <hr style="background-color: white;">
              <a href="{%  url 'orders_details' %}">My Orders</a>
              <hr style="background-color: white;">
              <a href="{%  url 'referrals' %}">Refer and Earn</a>
              <hr style="background-color: white;">
    
            </div>
    
          </div>
        </div>
      </div>
    
    
      
      <div class="col-lg-5 mt-2" id="addAddress">
        <div class="card">
          <div class="card-body">
    
            <form action="{% url 'add_address' %}" method ="POST">
              {% csrf_token %}
          
          <div class="form-group">
              <label>First name</label>
              {{form.first_name}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
              <label>Last name</label>
              {{form.last_name}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
              <label>Email</label>
              {{form.email}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
              <label>Phone</label>
              {{form.phone}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
              <label>Address</label>
              {{form.address}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
              <label>City</label>
              {{form.city}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
              <label>State</label>
              {{form.state}}
          </div> <!-- form-group end.// -->
          <input type="submit" class ="btn btn-dark" value="Add Address">
          <!-- <a href=" url 'user_profile' user.id %}" class="btn btn-sm btn-danger float"> back</a> -->
          </form>
          
          </div>
        </div>
      </div>
    </div> 
      {% endblock %}

templates/user/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Ticker</title>

<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>-->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>
<script src="https://www.paypal.com/sdk/js?client-id=AdDM-ep8yvVyMoJDAai_jDbj589MTjoCP8wL8QLa_KZFTaELORwYzOtew8-t-ap-zq5TnWJxvWDm82Sy&currency=USD"></script>

  


</head>
<body>

<!-- navbar -->

{% include 'user/includes/navbar.html'%}





{% block contend %}
<!-- content -->
{% endblock %}



<!-- footer -->
{% include 'user/includes/footer.html' %}

<!-- <script> $(document).ready(function(){ $('#imageZoom').imageZoom(); }); </script> -->
</body>
</html>

templates/user/edit_address.html
{% extends 'user/base.html' %}
{% load static %}
{% block contend %}



<style>
  .sidenav {
    width: 15rem;
    height: 25rem;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    padding-top: 20px;

  }

  .sidenav a {
    padding: 6px 8px 6px 16px;
    text-decoration: none;
    font-size: 15px;
    color: #818181;
    display: block;
  }

  .sidenav a:hover {
    color: #f1f1f1;
  }



  @media screen and (max-height: 450px) {
    .sidenav {
      padding-top: 15px;
    }

    .sidenav a {
      font-size: 18px;
    }
  }
</style>



<div class="row">
  <div class="col-lg-3 mt-2">
    <div class="card" style="height: 100% ; width: 18rem;">
      <div class="card-body">


        <!-- <a href="#" class="btn btn-outline-dark my-3">User Profile</a><br>
              <a href="" class="btn btn-outline-dark my-3">Add Address</a><br>
              <a href="" class="btn btn-outline-dark my-3">Orders</a>
               -->

        <div class="sidenav">
          <a href="{% url 'user_profile' user.id %}" class="active">Profile Info</a>

          <a href="{% url 'add_address' %}" style="color: white;">Add New Address</a>
          <a href="{%  url 'orders_details' %}">My Orders</a>

        </div>

      </div>
    </div>
  </div>



  <div class="col-lg-5 mt-2" id="addAddress">
    <div class="card">
      <div class="card-body">

        <form action="" method="POST">
          {% csrf_token %}

          <div class="form-group">
            <label>First name</label>
            {{form.first_name}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
            <label>Last name</label>
            {{form.last_name}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
            <label>Email</label>
            {{form.email}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
            <label>Phone</label>
            {{form.phone}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
            <label>Address</label>
            {{form.address}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
            <label>City</label>
            {{form.city}}
          </div> <!-- form-group end.// -->
          <div class="form-group">
            <label>State</label>
            {{form.state}}
          </div> <!-- form-group end.// -->
          <input type="submit" class="btn btn-dark" value="Add Address">
          <!-- <a href=" url 'user_profile' user.id %}" class="btn btn-sm btn-danger float"> back</a> -->
        </form>

      </div>
    </div>
  </div>



</div>

<footer class="section-footer border-top" id="footer" style="max-height: 100px; ">
	<div class="container">
		<p class="float-md-right"> 
			&copy Copyright 2021 All rights reserved
		</p>
		<p>
			<a href="#">Terms and conditions</a>
		</p>
	</div>


{% endblock %}

templates/user/edit_profile.html
{% extends 'user/base.html' %}
{% load static %}
{% block contend %}



<style>
  .sidenav {
    width: 15rem;
    height: 25rem;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    padding-top: 20px;

  }

  .sidenav a {
    padding: 6px 8px 6px 16px;
    text-decoration: none;
    font-size: 15px;
    color: #818181;
    display: block;
  }

  .sidenav a:hover {
    color: #f1f1f1;
  }



  @media screen and (max-height: 450px) {
    .sidenav {
      padding-top: 15px;
    }

    .sidenav a {
      font-size: 18px;
    }
  }
</style>



<div class="row">
  <div class="col-lg-3">
    <div class="card" style="height: 100% ; width: 18rem;">
      <div class="card-body">


        <div class="sidenav">
          <a href="{% url 'user_profile' user.id %}" style="color: white;">Profile Info</a>
          <a style="color: blanchedalmond; font-size: small; margin-left: 10px;" onclick="add(1)">Saved Address</a>
          <hr>


          <a href="{% url 'add_address' %}">Add New Address</a>
          <a href="{%  url 'orders_details' %}">My Orders</a>

        </div>

      </div>
    </div>
  </div>

  <form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" class="btn btn-dark mt-2" value="submit" name="" id="">
  </form>


  


  {% endblock %}

templates/user/register.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Ticker</title>

<link href="{% static '/images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static '/js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

<!-- Bootstrap4 files-->
<script src="{% static '/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static '/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static '/fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static '/css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '/css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static '/js/script.js' %}" type="text/javascript"></script>



<body>


<header class="section-header">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div>
</div> <!-- container //  -->
</nav>
<section class="header-main border-bottom">
	<div class="container">
<div class="row align-items-center">
	<div class="col-lg-2 col-md-3 col-6">
		<a href="./" class="brand-wrap">
			<img class="logo" src="{% static 'images/logo.png' %} ">
		</a> <!-- brand-wrap.// -->
	</div>
	

</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->



</header> <!-- section-header.// -->



<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body">
		<header class="mb-4"><h4 class="card-title">Sign up</h4></header>
		<form action="{% url 'user_register' %}" method= "POST">
			{% csrf_token %}

				<div class="form-row">
					<div class="col form-group">
						<label>First name</label>
						{{ form.first_name }}
					</div> 

					<div class="col form-group">
						<label>Last name</label>
						{{ form.last_name }}
					</div> 
				</div> 

				<div class="form-group">
					<label>Email</label>
					
					{{ form.email }}
				</div> 
				{{form.email.errors}}

				<div class="form-group">
					<label>Phone</label>
					{{ form.phone }}					 
				</div> 
								
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Create password</label>
						{{ form.password }}
					</div> 

					<div class="form-group col-md-6">
						<label>Repeat password</label>
					    {{form.confirm_password}}
					</div> 
					<div class="form-group col-md-6">
						<label>Referral Code</label>
					    {{form.referral}}
					</div> 
				</div>

			    <div class="form-group">
			        <button type="submit" class="btn btn-dark btn-block"> Register  </button>
			    </div> 
					
			        {{form.non_field_errors}}
			</form>
		</article>
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="{% url 'user_login'%}">Log In</a></p>
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->



<script>
	$(document).ready(function(){
		$("#email").change(function () {
			var email = $(this).val();
			console.log(email)
	 
		  $.ajax({
			url: '/accounts/validate_email/',
			data: {
			  'email': email
			},
			dataType: 'json',
			success: function (data) {
			  if (data.is_taken) {
				alert("A user with this email already exists.");
			  }
			}
		  });
	 
		});
	});
	

	$(document).ready(function(){
		$('#id_referral').change(function () {
		  var code = $(this).val();
		  console.log(code)
	 
		  $.ajax({
			url: '/accounts/validate_referralcode/',
			
			data: {
			  'code': code
			},
			dataType: 'json',
		
			success: function (data) {
				console.log(data.valid)
			  if (!(data.valid)) {
				$('#id_referral').val('');
				  
				  alert('invalid referal code');
				  
			  }
			  else if (data ==null)
			  return
			}
		  });
	 
		});
	});
</script>
</body>

</html>

templates/user/reset_password_email.html
{% autoescape off %}



HI, {{user.first_name}},

Please click the link below to reset your Password.
http://{{domain}}{% url 'resetpassword_validate' uidb64=uid token=token %}

if not done by you, Ignore the email
{% endautoescape %}